baseURL = "https://skkuding.dev"
languageCode = 'ko-kr'
title = 'SKKUDING 스꾸딩'

[module]
[[module.imports]]
path = "github.com/nanxiaobei/hugo-paper"

[params]
color = 'gray'
github = 'skkuding'
description = '성균관대학교 코드당 프로젝트 팀 스꾸딩'
images = ['open-graph.png']
title = 'SKKUDING 스꾸딩'
avatar = 'skkuding@gmail.com'
name = '우리는 스꾸딩이에요! 👋'
bio = '성균관대학교 코드당 프로젝트 팀'

[menu]
[[menu.main]]
identifier = 'blog'
name = 'Blog'
url = '/post/'
weight = 1
[[menu.main]]
identifier = 'about'
name = 'About'
url = '/about/'
weight = 2
[[menu.main]]
identifier = "contact"
name = "Contact"
url = "https://pf.kakao.com/_UKraK"
weight = 3

[deployment]
[[deployment.targets]]
name = 'AWS S3'
URL = 's3://skkuding.dev?region=ap-northeast-2'
